name: fitbit
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: ^7.1.0
  bloc: ^8.1.2

  circular_countdown_timer: ^0.2.3
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.7.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^6.0.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.5
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  internet_connection_checker: ^1.0.0+1
  syncfusion_flutter_charts: ^22.1.36

dev_dependencies:
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/dumbbell.png
    - assets/images/fit_boy.svg
    - assets/images/facebook_icon.svg
    - assets/images/gmail_icon.svg
    - assets/images/fit_boy.png
    - assets/images/fit_boy2.png
    - assets/images/fit_boy3.png
    - assets/images/abs_workout_icon.png
    - assets/images/lower_workout_icon.png
    - assets/images/finish_workout.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
